[package]
name = "tennis_questions_backend"
version = "0.1.0"
authors = ["Tijmen Stor <tm.stor@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.2"
serde_json = "1.0"
